BEGIN;
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD Zero Clause License', '0BSD', 'http://spdx.org/licenses/0BSD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Attribution Assurance License', 'AAL', 'http://spdx.org/licenses/AAL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Amazon Digital Services License', 'ADSL', 'http://spdx.org/licenses/ADSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academic Free License v1.1', 'AFL-1.1', 'http://spdx.org/licenses/AFL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academic Free License v1.2', 'AFL-1.2', 'http://spdx.org/licenses/AFL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academic Free License v2.0', 'AFL-2.0', 'http://spdx.org/licenses/AFL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academic Free License v2.1', 'AFL-2.1', 'http://spdx.org/licenses/AFL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academic Free License v3.0', 'AFL-3.0', 'http://spdx.org/licenses/AFL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Affero General Public License v1.0', 'AGPL-1.0', 'http://spdx.org/licenses/AGPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Affero General Public License v1.0 only', 'AGPL-1.0-only', 'http://spdx.org/licenses/AGPL-1.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Affero General Public License v1.0 or later', 'AGPL-1.0-or-later', 'http://spdx.org/licenses/AGPL-1.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Affero General Public License v3.0', 'AGPL-3.0', 'http://spdx.org/licenses/AGPL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Affero General Public License v3.0 only', 'AGPL-3.0-only', 'http://spdx.org/licenses/AGPL-3.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Affero General Public License v3.0 or later', 'AGPL-3.0-or-later', 'http://spdx.org/licenses/AGPL-3.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('AMD''s plpa_map.c License', 'AMDPLPA', 'http://spdx.org/licenses/AMDPLPA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apple MIT License', 'AML', 'http://spdx.org/licenses/AML.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Academy of Motion Picture Arts and Sciences BSD', 'AMPAS', 'http://spdx.org/licenses/AMPAS.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ANTLR Software Rights Notice', 'ANTLR-PD', 'http://spdx.org/licenses/ANTLR-PD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Adobe Postscript AFM License', 'APAFML', 'http://spdx.org/licenses/APAFML.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Adaptive Public License 1.0', 'APL-1.0', 'http://spdx.org/licenses/APL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apple Public Source License 1.0', 'APSL-1.0', 'http://spdx.org/licenses/APSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apple Public Source License 1.1', 'APSL-1.1', 'http://spdx.org/licenses/APSL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apple Public Source License 1.2', 'APSL-1.2', 'http://spdx.org/licenses/APSL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apple Public Source License 2.0', 'APSL-2.0', 'http://spdx.org/licenses/APSL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Abstyles License', 'Abstyles', 'http://spdx.org/licenses/Abstyles.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Adobe Systems Incorporated Source Code License Agreement', 'Adobe-2006', 'http://spdx.org/licenses/Adobe-2006.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Adobe Glyph List License', 'Adobe-Glyph', 'http://spdx.org/licenses/Adobe-Glyph.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Afmparse License', 'Afmparse', 'http://spdx.org/licenses/Afmparse.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Aladdin Free Public License', 'Aladdin', 'http://spdx.org/licenses/Aladdin.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apache License 1.0', 'Apache-1.0', 'http://spdx.org/licenses/Apache-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apache License 1.1', 'Apache-1.1', 'http://spdx.org/licenses/Apache-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Apache License 2.0', 'Apache-2.0', 'http://spdx.org/licenses/Apache-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Artistic License 1.0', 'Artistic-1.0', 'http://spdx.org/licenses/Artistic-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Artistic License 1.0 (Perl)', 'Artistic-1.0-Perl', 'http://spdx.org/licenses/Artistic-1.0-Perl.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Artistic License 1.0 w/clause 8', 'Artistic-1.0-cl8', 'http://spdx.org/licenses/Artistic-1.0-cl8.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Artistic License 2.0', 'Artistic-2.0', 'http://spdx.org/licenses/Artistic-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 1-Clause License', 'BSD-1-Clause', 'http://spdx.org/licenses/BSD-1-Clause.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 2-Clause "Simplified" License', 'BSD-2-Clause', 'http://spdx.org/licenses/BSD-2-Clause.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 2-Clause FreeBSD License', 'BSD-2-Clause-FreeBSD', 'http://spdx.org/licenses/BSD-2-Clause-FreeBSD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 2-Clause NetBSD License', 'BSD-2-Clause-NetBSD', 'http://spdx.org/licenses/BSD-2-Clause-NetBSD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD-2-Clause Plus Patent License', 'BSD-2-Clause-Patent', 'http://spdx.org/licenses/BSD-2-Clause-Patent.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause "New" or "Revised" License', 'BSD-3-Clause', 'http://spdx.org/licenses/BSD-3-Clause.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD with attribution', 'BSD-3-Clause-Attribution', 'http://spdx.org/licenses/BSD-3-Clause-Attribution.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause Clear License', 'BSD-3-Clause-Clear', 'http://spdx.org/licenses/BSD-3-Clause-Clear.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Lawrence Berkeley National Labs BSD variant license', 'BSD-3-Clause-LBNL', 'http://spdx.org/licenses/BSD-3-Clause-LBNL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause No Nuclear License', 'BSD-3-Clause-No-Nuclear-License', 'http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause No Nuclear License 2014', 'BSD-3-Clause-No-Nuclear-License-2014', 'http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause No Nuclear Warranty', 'BSD-3-Clause-No-Nuclear-Warranty', 'http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-Warranty.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 3-Clause Open MPI variant', 'BSD-3-Clause-Open-MPI', 'http://spdx.org/licenses/BSD-3-Clause-Open-MPI.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD 4-Clause "Original" or "Old" License', 'BSD-4-Clause', 'http://spdx.org/licenses/BSD-4-Clause.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD-4-Clause (University of California-Specific)', 'BSD-4-Clause-UC', 'http://spdx.org/licenses/BSD-4-Clause-UC.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD Protection License', 'BSD-Protection', 'http://spdx.org/licenses/BSD-Protection.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BSD Source Code Attribution', 'BSD-Source-Code', 'http://spdx.org/licenses/BSD-Source-Code.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Boost Software License 1.0', 'BSL-1.0', 'http://spdx.org/licenses/BSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Bahyph License', 'Bahyph', 'http://spdx.org/licenses/Bahyph.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Barr License', 'Barr', 'http://spdx.org/licenses/Barr.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Beerware License', 'Beerware', 'http://spdx.org/licenses/Beerware.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BitTorrent Open Source License v1.0', 'BitTorrent-1.0', 'http://spdx.org/licenses/BitTorrent-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('BitTorrent Open Source License v1.1', 'BitTorrent-1.1', 'http://spdx.org/licenses/BitTorrent-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Blue Oak Model License 1.0.0', 'BlueOak-1.0.0', 'http://spdx.org/licenses/BlueOak-1.0.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Borceux license', 'Borceux', 'http://spdx.org/licenses/Borceux.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Computer Associates Trusted Open Source License 1.1', 'CATOSL-1.1', 'http://spdx.org/licenses/CATOSL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution 1.0 Generic', 'CC-BY-1.0', 'http://spdx.org/licenses/CC-BY-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution 2.0 Generic', 'CC-BY-2.0', 'http://spdx.org/licenses/CC-BY-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution 2.5 Generic', 'CC-BY-2.5', 'http://spdx.org/licenses/CC-BY-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution 3.0 Unported', 'CC-BY-3.0', 'http://spdx.org/licenses/CC-BY-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution 4.0 International', 'CC-BY-4.0', 'http://spdx.org/licenses/CC-BY-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial 1.0 Generic', 'CC-BY-NC-1.0', 'http://spdx.org/licenses/CC-BY-NC-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial 2.0 Generic', 'CC-BY-NC-2.0', 'http://spdx.org/licenses/CC-BY-NC-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial 2.5 Generic', 'CC-BY-NC-2.5', 'http://spdx.org/licenses/CC-BY-NC-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial 3.0 Unported', 'CC-BY-NC-3.0', 'http://spdx.org/licenses/CC-BY-NC-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial 4.0 International', 'CC-BY-NC-4.0', 'http://spdx.org/licenses/CC-BY-NC-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic', 'CC-BY-NC-ND-1.0', 'http://spdx.org/licenses/CC-BY-NC-ND-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic', 'CC-BY-NC-ND-2.0', 'http://spdx.org/licenses/CC-BY-NC-ND-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic', 'CC-BY-NC-ND-2.5', 'http://spdx.org/licenses/CC-BY-NC-ND-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported', 'CC-BY-NC-ND-3.0', 'http://spdx.org/licenses/CC-BY-NC-ND-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial No Derivatives 4.0 International', 'CC-BY-NC-ND-4.0', 'http://spdx.org/licenses/CC-BY-NC-ND-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial Share Alike 1.0 Generic', 'CC-BY-NC-SA-1.0', 'http://spdx.org/licenses/CC-BY-NC-SA-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial Share Alike 2.0 Generic', 'CC-BY-NC-SA-2.0', 'http://spdx.org/licenses/CC-BY-NC-SA-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial Share Alike 2.5 Generic', 'CC-BY-NC-SA-2.5', 'http://spdx.org/licenses/CC-BY-NC-SA-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial Share Alike 3.0 Unported', 'CC-BY-NC-SA-3.0', 'http://spdx.org/licenses/CC-BY-NC-SA-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Non Commercial Share Alike 4.0 International', 'CC-BY-NC-SA-4.0', 'http://spdx.org/licenses/CC-BY-NC-SA-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution No Derivatives 1.0 Generic', 'CC-BY-ND-1.0', 'http://spdx.org/licenses/CC-BY-ND-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution No Derivatives 2.0 Generic', 'CC-BY-ND-2.0', 'http://spdx.org/licenses/CC-BY-ND-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution No Derivatives 2.5 Generic', 'CC-BY-ND-2.5', 'http://spdx.org/licenses/CC-BY-ND-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution No Derivatives 3.0 Unported', 'CC-BY-ND-3.0', 'http://spdx.org/licenses/CC-BY-ND-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution No Derivatives 4.0 International', 'CC-BY-ND-4.0', 'http://spdx.org/licenses/CC-BY-ND-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Share Alike 1.0 Generic', 'CC-BY-SA-1.0', 'http://spdx.org/licenses/CC-BY-SA-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Share Alike 2.0 Generic', 'CC-BY-SA-2.0', 'http://spdx.org/licenses/CC-BY-SA-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Share Alike 2.5 Generic', 'CC-BY-SA-2.5', 'http://spdx.org/licenses/CC-BY-SA-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Share Alike 3.0 Unported', 'CC-BY-SA-3.0', 'http://spdx.org/licenses/CC-BY-SA-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Attribution Share Alike 4.0 International', 'CC-BY-SA-4.0', 'http://spdx.org/licenses/CC-BY-SA-4.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Public Domain Dedication and Certification', 'CC-PDDC', 'http://spdx.org/licenses/CC-PDDC.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Creative Commons Zero v1.0 Universal', 'CC0-1.0', 'http://spdx.org/licenses/CC0-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Common Development and Distribution License 1.0', 'CDDL-1.0', 'http://spdx.org/licenses/CDDL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Common Development and Distribution License 1.1', 'CDDL-1.1', 'http://spdx.org/licenses/CDDL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Community Data License Agreement Permissive 1.0', 'CDLA-Permissive-1.0', 'http://spdx.org/licenses/CDLA-Permissive-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Community Data License Agreement Sharing 1.0', 'CDLA-Sharing-1.0', 'http://spdx.org/licenses/CDLA-Sharing-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL Free Software License Agreement v1.0', 'CECILL-1.0', 'http://spdx.org/licenses/CECILL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL Free Software License Agreement v1.1', 'CECILL-1.1', 'http://spdx.org/licenses/CECILL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL Free Software License Agreement v2.0', 'CECILL-2.0', 'http://spdx.org/licenses/CECILL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL Free Software License Agreement v2.1', 'CECILL-2.1', 'http://spdx.org/licenses/CECILL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL-B Free Software License Agreement', 'CECILL-B', 'http://spdx.org/licenses/CECILL-B.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CeCILL-C Free Software License Agreement', 'CECILL-C', 'http://spdx.org/licenses/CECILL-C.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CERN Open Hardware Licence v1.1', 'CERN-OHL-1.1', 'http://spdx.org/licenses/CERN-OHL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CERN Open Hardware Licence v1.2', 'CERN-OHL-1.2', 'http://spdx.org/licenses/CERN-OHL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CNRI Jython License', 'CNRI-Jython', 'http://spdx.org/licenses/CNRI-Jython.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CNRI Python License', 'CNRI-Python', 'http://spdx.org/licenses/CNRI-Python.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CNRI Python Open Source GPL Compatible License Agreement', 'CNRI-Python-GPL-Compatible', 'http://spdx.org/licenses/CNRI-Python-GPL-Compatible.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Common Public Attribution License 1.0', 'CPAL-1.0', 'http://spdx.org/licenses/CPAL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Common Public License 1.0', 'CPL-1.0', 'http://spdx.org/licenses/CPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Code Project Open License 1.02', 'CPOL-1.02', 'http://spdx.org/licenses/CPOL-1.02.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CUA Office Public License v1.0', 'CUA-OPL-1.0', 'http://spdx.org/licenses/CUA-OPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Caldera License', 'Caldera', 'http://spdx.org/licenses/Caldera.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Clarified Artistic License', 'ClArtistic', 'http://spdx.org/licenses/ClArtistic.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Condor Public License v1.1', 'Condor-1.1', 'http://spdx.org/licenses/Condor-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Crossword License', 'Crossword', 'http://spdx.org/licenses/Crossword.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CrystalStacker License', 'CrystalStacker', 'http://spdx.org/licenses/CrystalStacker.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Cube License', 'Cube', 'http://spdx.org/licenses/Cube.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Deutsche Freie Software Lizenz', 'D-FSL-1.0', 'http://spdx.org/licenses/D-FSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('DOC License', 'DOC', 'http://spdx.org/licenses/DOC.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('DSDP License', 'DSDP', 'http://spdx.org/licenses/DSDP.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Dotseqn License', 'Dotseqn', 'http://spdx.org/licenses/Dotseqn.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Educational Community License v1.0', 'ECL-1.0', 'http://spdx.org/licenses/ECL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Educational Community License v2.0', 'ECL-2.0', 'http://spdx.org/licenses/ECL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Eiffel Forum License v1.0', 'EFL-1.0', 'http://spdx.org/licenses/EFL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Eiffel Forum License v2.0', 'EFL-2.0', 'http://spdx.org/licenses/EFL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Eclipse Public License 1.0', 'EPL-1.0', 'http://spdx.org/licenses/EPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Eclipse Public License 2.0', 'EPL-2.0', 'http://spdx.org/licenses/EPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('EU DataGrid Software License', 'EUDatagrid', 'http://spdx.org/licenses/EUDatagrid.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('European Union Public License 1.0', 'EUPL-1.0', 'http://spdx.org/licenses/EUPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('European Union Public License 1.1', 'EUPL-1.1', 'http://spdx.org/licenses/EUPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('European Union Public License 1.2', 'EUPL-1.2', 'http://spdx.org/licenses/EUPL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Entessa Public License v1.0', 'Entessa', 'http://spdx.org/licenses/Entessa.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Erlang Public License v1.1', 'ErlPL-1.1', 'http://spdx.org/licenses/ErlPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Eurosym License', 'Eurosym', 'http://spdx.org/licenses/Eurosym.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('FSF All Permissive License', 'FSFAP', 'http://spdx.org/licenses/FSFAP.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('FSF Unlimited License', 'FSFUL', 'http://spdx.org/licenses/FSFUL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('FSF Unlimited License (with License Retention)', 'FSFULLR', 'http://spdx.org/licenses/FSFULLR.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Freetype Project License', 'FTL', 'http://spdx.org/licenses/FTL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Fair License', 'Fair', 'http://spdx.org/licenses/Fair.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Frameworx Open License 1.0', 'Frameworx-1.0', 'http://spdx.org/licenses/Frameworx-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('FreeImage Public License v1.0', 'FreeImage', 'http://spdx.org/licenses/FreeImage.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.1', 'GFDL-1.1', 'http://spdx.org/licenses/GFDL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.1 only', 'GFDL-1.1-only', 'http://spdx.org/licenses/GFDL-1.1-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.1 or later', 'GFDL-1.1-or-later', 'http://spdx.org/licenses/GFDL-1.1-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.2', 'GFDL-1.2', 'http://spdx.org/licenses/GFDL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.2 only', 'GFDL-1.2-only', 'http://spdx.org/licenses/GFDL-1.2-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.2 or later', 'GFDL-1.2-or-later', 'http://spdx.org/licenses/GFDL-1.2-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.3', 'GFDL-1.3', 'http://spdx.org/licenses/GFDL-1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.3 only', 'GFDL-1.3-only', 'http://spdx.org/licenses/GFDL-1.3-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Free Documentation License v1.3 or later', 'GFDL-1.3-or-later', 'http://spdx.org/licenses/GFDL-1.3-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GL2PS License', 'GL2PS', 'http://spdx.org/licenses/GL2PS.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v1.0 only', 'GPL-1.0', 'http://spdx.org/licenses/GPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v1.0 or later', 'GPL-1.0+', 'http://spdx.org/licenses/GPL-1.0+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v1.0 only', 'GPL-1.0-only', 'http://spdx.org/licenses/GPL-1.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v1.0 or later', 'GPL-1.0-or-later', 'http://spdx.org/licenses/GPL-1.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 only', 'GPL-2.0', 'http://spdx.org/licenses/GPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 or later', 'GPL-2.0+', 'http://spdx.org/licenses/GPL-2.0+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 only', 'GPL-2.0-only', 'http://spdx.org/licenses/GPL-2.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 or later', 'GPL-2.0-or-later', 'http://spdx.org/licenses/GPL-2.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 w/GCC Runtime Library exception', 'GPL-2.0-with-GCC-exception', 'http://spdx.org/licenses/GPL-2.0-with-GCC-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 w/Autoconf exception', 'GPL-2.0-with-autoconf-exception', 'http://spdx.org/licenses/GPL-2.0-with-autoconf-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 w/Bison exception', 'GPL-2.0-with-bison-exception', 'http://spdx.org/licenses/GPL-2.0-with-bison-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 w/Classpath exception', 'GPL-2.0-with-classpath-exception', 'http://spdx.org/licenses/GPL-2.0-with-classpath-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v2.0 w/Font exception', 'GPL-2.0-with-font-exception', 'http://spdx.org/licenses/GPL-2.0-with-font-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 only', 'GPL-3.0', 'http://spdx.org/licenses/GPL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 or later', 'GPL-3.0+', 'http://spdx.org/licenses/GPL-3.0+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 only', 'GPL-3.0-only', 'http://spdx.org/licenses/GPL-3.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 or later', 'GPL-3.0-or-later', 'http://spdx.org/licenses/GPL-3.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 w/GCC Runtime Library exception', 'GPL-3.0-with-GCC-exception', 'http://spdx.org/licenses/GPL-3.0-with-GCC-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU General Public License v3.0 w/Autoconf exception', 'GPL-3.0-with-autoconf-exception', 'http://spdx.org/licenses/GPL-3.0-with-autoconf-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Giftware License', 'Giftware', 'http://spdx.org/licenses/Giftware.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('3dfx Glide License', 'Glide', 'http://spdx.org/licenses/Glide.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Glulxe License', 'Glulxe', 'http://spdx.org/licenses/Glulxe.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Historical Permission Notice and Disclaimer', 'HPND', 'http://spdx.org/licenses/HPND.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Historical Permission Notice and Disclaimer - sell variant', 'HPND-sell-variant', 'http://spdx.org/licenses/HPND-sell-variant.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Haskell Language Report License', 'HaskellReport', 'http://spdx.org/licenses/HaskellReport.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('IBM PowerPC Initialization and Boot Software', 'IBM-pibs', 'http://spdx.org/licenses/IBM-pibs.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ICU License', 'ICU', 'http://spdx.org/licenses/ICU.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Independent JPEG Group License', 'IJG', 'http://spdx.org/licenses/IJG.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('IPA Font License', 'IPA', 'http://spdx.org/licenses/IPA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('IBM Public License v1.0', 'IPL-1.0', 'http://spdx.org/licenses/IPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ISC License', 'ISC', 'http://spdx.org/licenses/ISC.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ImageMagick License', 'ImageMagick', 'http://spdx.org/licenses/ImageMagick.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Imlib2 License', 'Imlib2', 'http://spdx.org/licenses/Imlib2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Info-ZIP License', 'Info-ZIP', 'http://spdx.org/licenses/Info-ZIP.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Intel Open Source License', 'Intel', 'http://spdx.org/licenses/Intel.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Intel ACPI Software License Agreement', 'Intel-ACPI', 'http://spdx.org/licenses/Intel-ACPI.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Interbase Public License v1.0', 'Interbase-1.0', 'http://spdx.org/licenses/Interbase-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Japan Network Information Center License', 'JPNIC', 'http://spdx.org/licenses/JPNIC.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('JSON License', 'JSON', 'http://spdx.org/licenses/JSON.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('JasPer License', 'JasPer-2.0', 'http://spdx.org/licenses/JasPer-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Licence Art Libre 1.2', 'LAL-1.2', 'http://spdx.org/licenses/LAL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Licence Art Libre 1.3', 'LAL-1.3', 'http://spdx.org/licenses/LAL-1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Library General Public License v2 only', 'LGPL-2.0', 'http://spdx.org/licenses/LGPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Library General Public License v2 or later', 'LGPL-2.0+', 'http://spdx.org/licenses/LGPL-2.0+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Library General Public License v2 only', 'LGPL-2.0-only', 'http://spdx.org/licenses/LGPL-2.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Library General Public License v2 or later', 'LGPL-2.0-or-later', 'http://spdx.org/licenses/LGPL-2.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v2.1 only', 'LGPL-2.1', 'http://spdx.org/licenses/LGPL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Library General Public License v2.1 or later', 'LGPL-2.1+', 'http://spdx.org/licenses/LGPL-2.1+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v2.1 only', 'LGPL-2.1-only', 'http://spdx.org/licenses/LGPL-2.1-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v2.1 or later', 'LGPL-2.1-or-later', 'http://spdx.org/licenses/LGPL-2.1-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v3.0 only', 'LGPL-3.0', 'http://spdx.org/licenses/LGPL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v3.0 or later', 'LGPL-3.0+', 'http://spdx.org/licenses/LGPL-3.0+.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v3.0 only', 'LGPL-3.0-only', 'http://spdx.org/licenses/LGPL-3.0-only.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('GNU Lesser General Public License v3.0 or later', 'LGPL-3.0-or-later', 'http://spdx.org/licenses/LGPL-3.0-or-later.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Lesser General Public License For Linguistic Resources', 'LGPLLR', 'http://spdx.org/licenses/LGPLLR.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Lucent Public License Version 1.0', 'LPL-1.0', 'http://spdx.org/licenses/LPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Lucent Public License v1.02', 'LPL-1.02', 'http://spdx.org/licenses/LPL-1.02.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('LaTeX Project Public License v1.0', 'LPPL-1.0', 'http://spdx.org/licenses/LPPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('LaTeX Project Public License v1.1', 'LPPL-1.1', 'http://spdx.org/licenses/LPPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('LaTeX Project Public License v1.2', 'LPPL-1.2', 'http://spdx.org/licenses/LPPL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('LaTeX Project Public License v1.3a', 'LPPL-1.3a', 'http://spdx.org/licenses/LPPL-1.3a.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('LaTeX Project Public License v1.3c', 'LPPL-1.3c', 'http://spdx.org/licenses/LPPL-1.3c.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Latex2e License', 'Latex2e', 'http://spdx.org/licenses/Latex2e.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Leptonica License', 'Leptonica', 'http://spdx.org/licenses/Leptonica.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Licence Libre du Québec – Permissive version 1.1', 'LiLiQ-P-1.1', 'http://spdx.org/licenses/LiLiQ-P-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Licence Libre du Québec – Réciprocité version 1.1', 'LiLiQ-R-1.1', 'http://spdx.org/licenses/LiLiQ-R-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Licence Libre du Québec – Réciprocité forte version 1.1', 'LiLiQ-Rplus-1.1', 'http://spdx.org/licenses/LiLiQ-Rplus-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('libpng License', 'Libpng', 'http://spdx.org/licenses/Libpng.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Linux Kernel Variant of OpenIB.org license', 'Linux-OpenIB', 'http://spdx.org/licenses/Linux-OpenIB.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('MIT License', 'MIT', 'http://spdx.org/licenses/MIT.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('MIT No Attribution', 'MIT-0', 'http://spdx.org/licenses/MIT-0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('CMU License', 'MIT-CMU', 'http://spdx.org/licenses/MIT-CMU.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Enlightenment License (e16)', 'MIT-advertising', 'http://spdx.org/licenses/MIT-advertising.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('enna License', 'MIT-enna', 'http://spdx.org/licenses/MIT-enna.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('feh License', 'MIT-feh', 'http://spdx.org/licenses/MIT-feh.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('MIT +no-false-attribs license', 'MITNFA', 'http://spdx.org/licenses/MITNFA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mozilla Public License 1.0', 'MPL-1.0', 'http://spdx.org/licenses/MPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mozilla Public License 1.1', 'MPL-1.1', 'http://spdx.org/licenses/MPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mozilla Public License 2.0', 'MPL-2.0', 'http://spdx.org/licenses/MPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mozilla Public License 2.0 (no copyleft exception)', 'MPL-2.0-no-copyleft-exception', 'http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Microsoft Public License', 'MS-PL', 'http://spdx.org/licenses/MS-PL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Microsoft Reciprocal License', 'MS-RL', 'http://spdx.org/licenses/MS-RL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Matrix Template Library License', 'MTLL', 'http://spdx.org/licenses/MTLL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('MakeIndex License', 'MakeIndex', 'http://spdx.org/licenses/MakeIndex.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('The MirOS Licence', 'MirOS', 'http://spdx.org/licenses/MirOS.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Motosoto License', 'Motosoto', 'http://spdx.org/licenses/Motosoto.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mulan Permissive Software License, Version 1', 'MulanPSL-1.0', 'http://spdx.org/licenses/MulanPSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Multics License', 'Multics', 'http://spdx.org/licenses/Multics.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Mup License', 'Mup', 'http://spdx.org/licenses/Mup.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('NASA Open Source Agreement 1.3', 'NASA-1.3', 'http://spdx.org/licenses/NASA-1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Net Boolean Public License v1', 'NBPL-1.0', 'http://spdx.org/licenses/NBPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('University of Illinois/NCSA Open Source License', 'NCSA', 'http://spdx.org/licenses/NCSA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Nethack General Public License', 'NGPL', 'http://spdx.org/licenses/NGPL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Norwegian Licence for Open Government Data', 'NLOD-1.0', 'http://spdx.org/licenses/NLOD-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('No Limit Public License', 'NLPL', 'http://spdx.org/licenses/NLPL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Netizen Open Source License', 'NOSL', 'http://spdx.org/licenses/NOSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Netscape Public License v1.0', 'NPL-1.0', 'http://spdx.org/licenses/NPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Netscape Public License v1.1', 'NPL-1.1', 'http://spdx.org/licenses/NPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Non-Profit Open Software License 3.0', 'NPOSL-3.0', 'http://spdx.org/licenses/NPOSL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('NRL License', 'NRL', 'http://spdx.org/licenses/NRL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('NTP License', 'NTP', 'http://spdx.org/licenses/NTP.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('NTP No Attribution', 'NTP-0', 'http://spdx.org/licenses/NTP-0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Naumen Public License', 'Naumen', 'http://spdx.org/licenses/Naumen.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Net-SNMP License', 'Net-SNMP', 'http://spdx.org/licenses/Net-SNMP.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('NetCDF license', 'NetCDF', 'http://spdx.org/licenses/NetCDF.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Newsletr License', 'Newsletr', 'http://spdx.org/licenses/Newsletr.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Nokia Open Source License', 'Nokia', 'http://spdx.org/licenses/Nokia.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Noweb License', 'Noweb', 'http://spdx.org/licenses/Noweb.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Nunit License', 'Nunit', 'http://spdx.org/licenses/Nunit.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open CASCADE Technology Public License', 'OCCT-PL', 'http://spdx.org/licenses/OCCT-PL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('OCLC Research Public License 2.0', 'OCLC-2.0', 'http://spdx.org/licenses/OCLC-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Data Commons Attribution License v1.0', 'ODC-By-1.0', 'http://spdx.org/licenses/ODC-By-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ODC Open Database License v1.0', 'ODbL-1.0', 'http://spdx.org/licenses/ODbL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.0', 'OFL-1.0', 'http://spdx.org/licenses/OFL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.0 with Reserved Font Name', 'OFL-1.0-RFN', 'http://spdx.org/licenses/OFL-1.0-RFN.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.0 with no Reserved Font Name', 'OFL-1.0-no-RFN', 'http://spdx.org/licenses/OFL-1.0-no-RFN.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.1', 'OFL-1.1', 'http://spdx.org/licenses/OFL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.1 with Reserved Font Name', 'OFL-1.1-RFN', 'http://spdx.org/licenses/OFL-1.1-RFN.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SIL Open Font License 1.1 with no Reserved Font Name', 'OFL-1.1-no-RFN', 'http://spdx.org/licenses/OFL-1.1-no-RFN.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Government Licence - Canada', 'OGL-Canada-2.0', 'http://spdx.org/licenses/OGL-Canada-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Government Licence v1.0', 'OGL-UK-1.0', 'http://spdx.org/licenses/OGL-UK-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Government Licence v2.0', 'OGL-UK-2.0', 'http://spdx.org/licenses/OGL-UK-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Government Licence v3.0', 'OGL-UK-3.0', 'http://spdx.org/licenses/OGL-UK-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Group Test Suite License', 'OGTSL', 'http://spdx.org/licenses/OGTSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v1.1', 'OLDAP-1.1', 'http://spdx.org/licenses/OLDAP-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v1.2', 'OLDAP-1.2', 'http://spdx.org/licenses/OLDAP-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v1.3', 'OLDAP-1.3', 'http://spdx.org/licenses/OLDAP-1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v1.4', 'OLDAP-1.4', 'http://spdx.org/licenses/OLDAP-1.4.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)', 'OLDAP-2.0', 'http://spdx.org/licenses/OLDAP-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.0.1', 'OLDAP-2.0.1', 'http://spdx.org/licenses/OLDAP-2.0.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.1', 'OLDAP-2.1', 'http://spdx.org/licenses/OLDAP-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.2', 'OLDAP-2.2', 'http://spdx.org/licenses/OLDAP-2.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.2.1', 'OLDAP-2.2.1', 'http://spdx.org/licenses/OLDAP-2.2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License 2.2.2', 'OLDAP-2.2.2', 'http://spdx.org/licenses/OLDAP-2.2.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.3', 'OLDAP-2.3', 'http://spdx.org/licenses/OLDAP-2.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.4', 'OLDAP-2.4', 'http://spdx.org/licenses/OLDAP-2.4.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.5', 'OLDAP-2.5', 'http://spdx.org/licenses/OLDAP-2.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.6', 'OLDAP-2.6', 'http://spdx.org/licenses/OLDAP-2.6.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.7', 'OLDAP-2.7', 'http://spdx.org/licenses/OLDAP-2.7.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open LDAP Public License v2.8', 'OLDAP-2.8', 'http://spdx.org/licenses/OLDAP-2.8.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Market License', 'OML', 'http://spdx.org/licenses/OML.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Public License v1.0', 'OPL-1.0', 'http://spdx.org/licenses/OPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('OSET Public License version 2.1', 'OSET-PL-2.1', 'http://spdx.org/licenses/OSET-PL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Software License 1.0', 'OSL-1.0', 'http://spdx.org/licenses/OSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Software License 1.1', 'OSL-1.1', 'http://spdx.org/licenses/OSL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Software License 2.0', 'OSL-2.0', 'http://spdx.org/licenses/OSL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Software License 2.1', 'OSL-2.1', 'http://spdx.org/licenses/OSL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Open Software License 3.0', 'OSL-3.0', 'http://spdx.org/licenses/OSL-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('OpenSSL License', 'OpenSSL', 'http://spdx.org/licenses/OpenSSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('ODC Public Domain Dedication & License 1.0', 'PDDL-1.0', 'http://spdx.org/licenses/PDDL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('PHP License v3.0', 'PHP-3.0', 'http://spdx.org/licenses/PHP-3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('PHP License v3.01', 'PHP-3.01', 'http://spdx.org/licenses/PHP-3.01.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Python Software Foundation License 2.0', 'PSF-2.0', 'http://spdx.org/licenses/PSF-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('The Parity Public License 6.0.0', 'Parity-6.0.0', 'http://spdx.org/licenses/Parity-6.0.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Plexus Classworlds License', 'Plexus', 'http://spdx.org/licenses/Plexus.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('PostgreSQL License', 'PostgreSQL', 'http://spdx.org/licenses/PostgreSQL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Python License 2.0', 'Python-2.0', 'http://spdx.org/licenses/Python-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Q Public License 1.0', 'QPL-1.0', 'http://spdx.org/licenses/QPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Qhull License', 'Qhull', 'http://spdx.org/licenses/Qhull.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Red Hat eCos Public License v1.1', 'RHeCos-1.1', 'http://spdx.org/licenses/RHeCos-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Reciprocal Public License 1.1', 'RPL-1.1', 'http://spdx.org/licenses/RPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Reciprocal Public License 1.5', 'RPL-1.5', 'http://spdx.org/licenses/RPL-1.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('RealNetworks Public Source License v1.0', 'RPSL-1.0', 'http://spdx.org/licenses/RPSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('RSA Message-Digest License ', 'RSA-MD', 'http://spdx.org/licenses/RSA-MD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Ricoh Source Code Public License', 'RSCPL', 'http://spdx.org/licenses/RSCPL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Rdisc License', 'Rdisc', 'http://spdx.org/licenses/Rdisc.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Ruby License', 'Ruby', 'http://spdx.org/licenses/Ruby.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sax Public Domain Notice', 'SAX-PD', 'http://spdx.org/licenses/SAX-PD.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SCEA Shared Source License', 'SCEA', 'http://spdx.org/licenses/SCEA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SGI Free Software License B v1.0', 'SGI-B-1.0', 'http://spdx.org/licenses/SGI-B-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SGI Free Software License B v1.1', 'SGI-B-1.1', 'http://spdx.org/licenses/SGI-B-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SGI Free Software License B v2.0', 'SGI-B-2.0', 'http://spdx.org/licenses/SGI-B-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Solderpad Hardware License v0.5', 'SHL-0.5', 'http://spdx.org/licenses/SHL-0.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Solderpad Hardware License, Version 0.51', 'SHL-0.51', 'http://spdx.org/licenses/SHL-0.51.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sun Industry Standards Source License v1.1', 'SISSL', 'http://spdx.org/licenses/SISSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sun Industry Standards Source License v1.2', 'SISSL-1.2', 'http://spdx.org/licenses/SISSL-1.2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Standard ML of New Jersey License', 'SMLNJ', 'http://spdx.org/licenses/SMLNJ.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Secure Messaging Protocol Public License', 'SMPPL', 'http://spdx.org/licenses/SMPPL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SNIA Public License 1.1', 'SNIA', 'http://spdx.org/licenses/SNIA.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sun Public License v1.0', 'SPL-1.0', 'http://spdx.org/licenses/SPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SSH OpenSSH license', 'SSH-OpenSSH', 'http://spdx.org/licenses/SSH-OpenSSH.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SSH short notice', 'SSH-short', 'http://spdx.org/licenses/SSH-short.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Server Side Public License, v 1', 'SSPL-1.0', 'http://spdx.org/licenses/SSPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Scheme Widget Library (SWL) Software License Agreement', 'SWL', 'http://spdx.org/licenses/SWL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Saxpath License', 'Saxpath', 'http://spdx.org/licenses/Saxpath.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sendmail License', 'Sendmail', 'http://spdx.org/licenses/Sendmail.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sendmail License 8.23', 'Sendmail-8.23', 'http://spdx.org/licenses/Sendmail-8.23.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Simple Public License 2.0', 'SimPL-2.0', 'http://spdx.org/licenses/SimPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sleepycat License', 'Sleepycat', 'http://spdx.org/licenses/Sleepycat.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Spencer License 86', 'Spencer-86', 'http://spdx.org/licenses/Spencer-86.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Spencer License 94', 'Spencer-94', 'http://spdx.org/licenses/Spencer-94.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Spencer License 99', 'Spencer-99', 'http://spdx.org/licenses/Spencer-99.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Standard ML of New Jersey License', 'StandardML-NJ', 'http://spdx.org/licenses/StandardML-NJ.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SugarCRM Public License v1.1.3', 'SugarCRM-1.1.3', 'http://spdx.org/licenses/SugarCRM-1.1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('TAPR Open Hardware License v1.0', 'TAPR-OHL-1.0', 'http://spdx.org/licenses/TAPR-OHL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('TCL/TK License', 'TCL', 'http://spdx.org/licenses/TCL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('TCP Wrappers License', 'TCP-wrappers', 'http://spdx.org/licenses/TCP-wrappers.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('TMate Open Source License', 'TMate', 'http://spdx.org/licenses/TMate.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('TORQUE v2.5+ Software License v1.1', 'TORQUE-1.1', 'http://spdx.org/licenses/TORQUE-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Trusster Open Source License', 'TOSL', 'http://spdx.org/licenses/TOSL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Technische Universitaet Berlin License 1.0', 'TU-Berlin-1.0', 'http://spdx.org/licenses/TU-Berlin-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Technische Universitaet Berlin License 2.0', 'TU-Berlin-2.0', 'http://spdx.org/licenses/TU-Berlin-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Upstream Compatibility License v1.0', 'UCL-1.0', 'http://spdx.org/licenses/UCL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Universal Permissive License v1.0', 'UPL-1.0', 'http://spdx.org/licenses/UPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Unicode License Agreement - Data Files and Software (2015)', 'Unicode-DFS-2015', 'http://spdx.org/licenses/Unicode-DFS-2015.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Unicode License Agreement - Data Files and Software (2016)', 'Unicode-DFS-2016', 'http://spdx.org/licenses/Unicode-DFS-2016.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Unicode Terms of Use', 'Unicode-TOU', 'http://spdx.org/licenses/Unicode-TOU.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('The Unlicense', 'Unlicense', 'http://spdx.org/licenses/Unlicense.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('VOSTROM Public License for Open Source', 'VOSTROM', 'http://spdx.org/licenses/VOSTROM.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Vovida Software License v1.0', 'VSL-1.0', 'http://spdx.org/licenses/VSL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Vim License', 'Vim', 'http://spdx.org/licenses/Vim.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('W3C Software Notice and License (2002-12-31)', 'W3C', 'http://spdx.org/licenses/W3C.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('W3C Software Notice and License (1998-07-20)', 'W3C-19980720', 'http://spdx.org/licenses/W3C-19980720.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('W3C Software Notice and Document License (2015-05-13)', 'W3C-20150513', 'http://spdx.org/licenses/W3C-20150513.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Do What The F*ck You Want To Public License', 'WTFPL', 'http://spdx.org/licenses/WTFPL.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Sybase Open Watcom Public License 1.0', 'Watcom-1.0', 'http://spdx.org/licenses/Watcom-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Wsuipa License', 'Wsuipa', 'http://spdx.org/licenses/Wsuipa.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('X11 License', 'X11', 'http://spdx.org/licenses/X11.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('XFree86 License 1.1', 'XFree86-1.1', 'http://spdx.org/licenses/XFree86-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('XSkat License', 'XSkat', 'http://spdx.org/licenses/XSkat.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Xerox License', 'Xerox', 'http://spdx.org/licenses/Xerox.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('X.Net License', 'Xnet', 'http://spdx.org/licenses/Xnet.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Yahoo! Public License v1.0', 'YPL-1.0', 'http://spdx.org/licenses/YPL-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Yahoo! Public License v1.1', 'YPL-1.1', 'http://spdx.org/licenses/YPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zope Public License 1.1', 'ZPL-1.1', 'http://spdx.org/licenses/ZPL-1.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zope Public License 2.0', 'ZPL-2.0', 'http://spdx.org/licenses/ZPL-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zope Public License 2.1', 'ZPL-2.1', 'http://spdx.org/licenses/ZPL-2.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zed License', 'Zed', 'http://spdx.org/licenses/Zed.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zend License v2.0', 'Zend-2.0', 'http://spdx.org/licenses/Zend-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zimbra Public License v1.3', 'Zimbra-1.3', 'http://spdx.org/licenses/Zimbra-1.3.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Zimbra Public License v1.4', 'Zimbra-1.4', 'http://spdx.org/licenses/Zimbra-1.4.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('zlib License', 'Zlib', 'http://spdx.org/licenses/Zlib.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('SQLite Blessing', 'blessing', 'http://spdx.org/licenses/blessing.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('bzip2 and libbzip2 License v1.0.5', 'bzip2-1.0.5', 'http://spdx.org/licenses/bzip2-1.0.5.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('bzip2 and libbzip2 License v1.0.6', 'bzip2-1.0.6', 'http://spdx.org/licenses/bzip2-1.0.6.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('copyleft-next 0.3.0', 'copyleft-next-0.3.0', 'http://spdx.org/licenses/copyleft-next-0.3.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('copyleft-next 0.3.1', 'copyleft-next-0.3.1', 'http://spdx.org/licenses/copyleft-next-0.3.1.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('curl License', 'curl', 'http://spdx.org/licenses/curl.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('diffmark license', 'diffmark', 'http://spdx.org/licenses/diffmark.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('dvipdfm License', 'dvipdfm', 'http://spdx.org/licenses/dvipdfm.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('eCos license version 2.0', 'eCos-2.0', 'http://spdx.org/licenses/eCos-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('eGenix.com Public License 1.1.0', 'eGenix', 'http://spdx.org/licenses/eGenix.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('Etalab Open License 2.0', 'etalab-2.0', 'http://spdx.org/licenses/etalab-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('gSOAP Public License v1.3b', 'gSOAP-1.3b', 'http://spdx.org/licenses/gSOAP-1.3b.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('gnuplot License', 'gnuplot', 'http://spdx.org/licenses/gnuplot.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('iMatix Standard Function Library Agreement', 'iMatix', 'http://spdx.org/licenses/iMatix.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('PNG Reference Library version 2', 'libpng-2.0', 'http://spdx.org/licenses/libpng-2.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('libselinux public domain notice', 'libselinux-1.0', 'http://spdx.org/licenses/libselinux-1.0.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('libtiff License', 'libtiff', 'http://spdx.org/licenses/libtiff.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('mpich2 License', 'mpich2', 'http://spdx.org/licenses/mpich2.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('psfrag License', 'psfrag', 'http://spdx.org/licenses/psfrag.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('psutils License', 'psutils', 'http://spdx.org/licenses/psutils.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('wxWindows Library License', 'wxWindows', 'http://spdx.org/licenses/wxWindows.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('xinetd License', 'xinetd', 'http://spdx.org/licenses/xinetd.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('XPP License', 'xpp', 'http://spdx.org/licenses/xpp.json');
INSERT INTO "license" ("full_name", "identifier", "url") VALUES ('zlib/libpng License with Acknowledgement', 'zlib-acknowledgement', 'http://spdx.org/licenses/zlib-acknowledgement.json');
COMMIT;
