#!/usr/bin/env python

import requests
from pathlib import Path
from psycopg2.extensions import adapt

DIRPATH = Path(__file__).resolve().parent.parent
URL = "https://github.com/spdx/license-list-data/raw/master/json/licenses.json"
HEADER = """-- Common metadata for the BONSAI project: https://bonsai.uno/
-- Assumes schema from https://github.com/BONSAMURAIS/schema/
-- BONSAI mailing list: https://bonsai.groups.io/g/main/

-- After initial release, please make all changes following the pull request
-- workflow to allow for community review. Large changes will probably require
-- a BEP: https://github.com/BONSAMURAIS/enhancements

-- This file generated by python/create_common_licenses_metadata.py

"""

def prepare_statement(template, values):
    """Correctly escape things and keep as unicode.

    pyscopg2 has a default encoding of `latin-1`: https://github.com/psycopg/psycopg2/issues/331"""
    new_values = []
    for value in values:
        adapted = adapt(value)
        adapted.encoding = 'utf-8'
        new_values.append(adapted.getquoted().decode())

    return template.format(*new_values)


data = requests.get(URL).json()['licenses']

TEMPLATE = """INSERT INTO "license" ("full_name", "identifier", "url") VALUES ({}, {}, {});\n"""

with open(DIRPATH / "sql" / "common_metadata_licenses.sql", "w", encoding='utf-8') as f:
    f.write(HEADER)
    f.write("BEGIN;\n")
    for obj in data:
        f.write(prepare_statement(
            TEMPLATE,
            (adapt(obj['name']), adapt(obj['licenseId']), adapt(obj['detailsUrl']))
        ))
    f.write("COMMIT;\n")
