#!/usr/bin/env python

from pathlib import Path
from psycopg2.extensions import adapt
import io
import pyarrow.parquet as pq
import requests

DIRPATH = Path(__file__).resolve().parent.parent
URL = "https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/output/FedElemFlowListMaster.parquet?raw=true"
HEADER = """-- Common metadata for the BONSAI project: https://bonsai.uno/
-- Assumes schema from https://github.com/BONSAMURAIS/schema/
-- BONSAI mailing list: https://bonsai.groups.io/g/main/

-- After initial release, please make all changes following the pull request
-- workflow to allow for community review. Large changes will probably require
-- a BEP: https://github.com/BONSAMURAIS/enhancements

-- This file generated by python/create_common_biosphere_flows_metadata.py

"""
TEMPLATE = """INSERT INTO "flow_object" ("label", "CAS") VALUES ({}, {});\n"""

def prepare_statement(template, values):
    """Correctly escape things and keep as unicode.

    pyscopg2 has a default encoding of `latin-1`: https://github.com/psycopg/psycopg2/issues/331"""
    new_values = []
    for value in values:
        if value != None:
            adapted = adapt(value)
            adapted.encoding = 'utf-8'
            new_values.append(adapted.getquoted().decode())
        else:
            new_values.append('')
    return template.format(*new_values)


def _(s):
    try:
        return s.strip()
    except:
        return s


data = io.BytesIO(requests.get(URL).content)
table = pq.read_table(data).to_pandas()
ft = table.sort_values(["Flowable", "Context"]).drop_duplicates(['Flowable', 'CAS No'])


with open(DIRPATH / "sql" / "common_metadata_biosphere.sql", "w", encoding='utf-8') as f:
    f.write(HEADER)
    f.write("BEGIN;\n")

    for index, obj in ft.iterrows():
        f.write(prepare_statement(
            TEMPLATE,
            (_(obj['Flowable']), _(obj['CAS No']) or '')
        ))
    f.write("COMMIT;\n")
